# Generated by Django 5.2.7 on 2026-05-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_bio_img_alter_bio_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.TextField(default='Various'),
        ),
    ]
