# Generated by Django 6.0.4 on 2026-05-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_dish_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='img',
            field=models.FileField(default='profile_pics/profile.jpg', max_length=500, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='img',
            field=models.FileField(max_length=500, upload_to=''),
        ),
    ]
